pydatajson/core.py, tests/samples/several_datasets.json, tests/test_core.py
Issue: https://github.com/datosgobar/pydatajson/issues/48
=> Agrego método generate_catalog_indicators a DataJson

pydatajson/core.py, pydatajson/helpers.py, tests/samples/several_datasets.json, tests/test_core.py
Issue: #50 
Quedaría a discusión si el indicador `datasets_frecuencia_cant` debe contener llaves con valores nulos o no.
=> Indicadores de fecha

docs/MANUAL.md, pydatajson/ckan_utils.py, pydatajson/federation.py, tests/cassetes/ckan_integration/tearDown.yaml, tests/cassetes/ckan_integration/test_dataset_is_created_correctly.yaml, tests/cassetes/ckan_integration/test_dataset_is_updated_correctly.yaml, tests/cassetes/ckan_integration/test_groups_are_created.yaml, tests/cassetes/ckan_integration/test_resources_swapped_correctly.yaml, tests/test_ckan_integration.py, tests/test_ckan_utils.py, tests/test_federation.py
Hago cambios al manejo de ids de la función
=> 89 push dataset to ckan

pydatajson/ckan_utils.py, tests/test_ckan_utils.py
Agrego los campos del 1.1 que faltaban en `push_dataset_to_ckan()`
=> Se agregan los campos fileName y source para cumplir con 1.1

pydatajson/download.py
Agrega el módulo `download.py` con las funciones `download` y `download_to_file`.
Issue: https://github.com/datosgobar/pydatajson/issues/114
=> Agrega módulo download.py.

docs/MANUAL.md, pydatajson/ckan_utils.py, pydatajson/federation.py, tests/test_ckan_utils.py
Closes #91 
Agrega el parametro opcional `demote_themes`. En caso de ser True, los labels de los themes  correspondientes se pasan a CKAN como tags. En caso contrario, se pasan como groups.
=> 91 mover theme a keyword

tests/test_core.py, tests/test_validation.py
Closes #95 
Muevo tests de validación a `test_validation.py`.
=> 95 refactor de tests de validación

tests/support/factories/dataset_errors.py, tests/test_validation.py
Closes #155 
Agrega el pattern esperado al mensaje de error default que causaba que el test falle
=> Validar periodicity eventual con mayusculas

pydatajson/indicators.py, tests/test_indicators.py
Closes #169 
- Agrega la cantidad de distribuciones federadas a los indicadores.
- Agrega tests del comportamiento.
=> 169 distribuciones federadas cant

pydatajson/indicators.py, tests/test_indicators.py
Closes #184 
- Cambia la forma en que cuenta los fields para asignar `None` si el valor no está o es falsy.
- Actualiza los tests existentes.
=> 184 valor missing indicadores

pydatajson/schemas/dataset.json
- Agrega caracteres con tilde y ñ al patron permitido en keywords
=> Admito caracteres con tildes y ñ

pydatajson/ckan_reader.py, pydatajson/ckan_utils.py, pydatajson/helpers.py, tests/test_ckan_reader.py, tests/test_ckan_utils.py
Closes #188 
- Agrega tests para el módulo `ckan_reader`
- Arregla issues menores en `read_ckan_catalog` de `ckan_reader`
=> 188 tests ckan reader

pydatajson/schemas/dataset.json, tests/results/datasets.json, tests/results/datasets_filter_in.json, tests/results/datasets_filter_out.json, tests/results/get_dataset.json, tests/samples/full_data.json, tests/samples/invalid_keywords.json
Closes datosgobar/monitoreo-apertura#55
- Agrega casos de test con keywords con espacios. Actualiza los resultados para incorporar el cambio.
- Agrega el espacio a los caracteres permitidos en el jsonschema
=> Keyword validacion con espacios

docs/MANUAL.md, pydatajson/documentation.py, pydatajson/federation.py, tests/samples/organization_tree.json, tests/test_federation.py
Closes #208 
- Agrega método `push_organization_tree_to_ckan()`.
- Agrega tests de comportamiento.
=> 208 push organization tree to ckan

pydatajson/indicators.py, tests/test_indicators.py
- Refactor del cálculo de indicadores porcentuales
- Agrega el indicadores de `datasets_con_datos` a los tests
=> Datasets con datos pct fix

docs/MANUAL.md, pydatajson/federation.py, tests/samples/resource_sample.csv, tests/test_federation.py
Closes #200 
- Agrega el método `resources_upload()`
- Agrega tests de la funcionalidad.
=> 200 upload resources

docs/MANUAL.md, pydatajson/federation.py, pydatajson/helpers.py, tests/test_federation.py
Closes #201 
- Agrega un parámetro opcional `download_strategy` que determina para cada distribución si descargar y subir su archivo.
- Agrega tests de este nuevo parámetro.
=> 201 restore catalog file upload

docs/MANUAL.md, pydatajson/federation.py, tests/test_federation.py
Closes #217 
- Agrega método `remove_organizations_from_ckan`
- Agrega test del método
- Documentación
=> 217 remove organizations from ckan

pydatajson/schemas/catalog.json, pydatajson/schemas/dataset.json, pydatajson/schemas/distribution.json, pydatajson/schemas/mixed-types.json, pydatajson/schemas/required_fields_schema.json, tests/samples/empty_optional_string.json, tests/samples/invalid_keywords.json, tests/samples/minimum_data.json, tests/samples/several_assorted_errors.json, tests/samples/several_datasets.json, tests/samples/several_datasets_for_harvest.json, tests/support/factories/dataset_errors.py, tests/support/factories/distribution_errors.py, tests/support/factories/other_errors.py, tests/test_validation.py
Closes #230 
- Admite el string vacío como valor nulo.
- Incluye los identificadores de dataset y distribuciones como valores requeridos
- Actualiza los samples de los tests para tener en cuenta los cambios en las validaciones
=> 230 validar strings vacios

pydatajson/indicators.py, tests/test_indicators.py
Closes #242 
- Cambia los indicadores para que calculen el porcentaje de 0 a 1 en vez de 0 a 100
- Ajusta los valores esperados de los tests
=> 243 cambiar porcentaje de indicadores

pydatajson/core.py, pydatajson/helpers.py, pydatajson/indicator_generators.py, pydatajson/indicators.py, tests/samples/central.json, tests/samples/federated_1.json, tests/samples/federated_2.json, tests/samples/several_datasets.json, tests/test_indicators.py
Closes #243 
- Agrega un keyword argument para calcular los indicadores de federación usando los ids en lugar de los titulos
- Agrega samples y test para el comportamiento nuevo
=> 243 indicadores federacion

requirements.txt
Closes datosgobar/monitoreo-apertura#144
=> Saco las versiones fijadas de six y urllib

pydatajson/schemas/dataset.json, tests/samples/invalid_multiple_emails.json, tests/samples/invalid_whitespace_emails.json, tests/test_validation.py
=> 267 email validation

pydatajson/catalog_readme.py, pydatajson/core.py, pydatajson/helpers.py, pydatajson/indicators.py, pydatajson/reporting.py, pydatajson/status_indicators_generator.py, pydatajson/threading_helper.py, pydatajson/validation.py, pydatajson/validators/consistent_distribution_fields_validator.py, pydatajson/validators/distribution_download_urls_validator.py, pydatajson/validators/distribution_urls_validator.py, pydatajson/validators/landing_pages_validator.py, pydatajson/validators/simple_validator.py, pydatajson/validators/theme_ids_not_repeated_validator.py, pydatajson/validators/url_validator.py, tests/support/factories/core_files.py, tests/test_core.py, tests/test_helpers.py, tests/test_status_indicators_generator.py, tests/test_threading.py, tests/test_urls_validation.py, tests/test_validators.py
=> validacion electiva de ssl

pydatajson/backup.py, pydatajson/download.py
- Reformateo de código
- Simplifiación de la API
- Uso por línea de comandos
- Retry con back-off luego de un error de descarga 
Esta primera versión es incipiente, a ser usada inicialmente para detectar errores luego de su puesta en producción.
Closes #305
=> Mejoras sobre el script de backup
