datosgobar/pydatajson

- pydatajson/schemas/accrualPeriodicity.json
closes #58 
El archivo del que se tomó esta lista de frecuencias (https://github.com/datosgobar/paquete-apertura-datos/blob/master/standards/metadata/accrualPeriodicity.json) tiene una tilde faltante. Esto está generando problemas en la validación de datasets del Ministerio de Justicia como se describe en #58 
@abenassi este cambio es un impedimento para la correcta federación del portal de datos de Justicia. Requerimos una nueva versión de pydatajson disponible en PyPI, para luego actualizar las dependencias de `libreria-catalogos` en el servidor de federación, y que el data.json generado para Justicia sea del todo correcto. Se podrá empujar durante el día de hoy?
> Agrega tilde faltante a periocididad 'cada 15 días'

- pydatajson/core.py
- tests/results/catalog_readme.md
- tests/test_core.py
- tests/test_helpers.py
Cambios:
- Modifiqué el template de CATALOG README
- Agregué el indicador "datasets_no_federados" a generate_catalogs_indicators
- Agregué una variable global al módulo `core`: CENTRAL_CATALOG, para saber contra qué comparar para obtener estadísticas de federación.
Esta última decisión, la de la variable global, es la más polémica supongo. Tampoco es la muerte de nadie.
> Mejoras datasets no federados

- pydatajson/__init__.py
- pydatajson/core.py
- tests/test_core.py
- Agrego un método `dataset_is_updated` en `DataJson` para verificar si un dataset dentro del catálogo se encuentra actualizado.
- Expongo públicamente el método `parse_repeating_time_interval` de `helpers`.
> Métodos auxiliares usados para caluclar indicadores del PAD

- pydatajson/helpers.py
- tests/samples/invalid_catalog_empty.json
- tests/test_core.py
- Modifica el método `helpers.add_dicts` para que reemplaze los valores de tipo `None` por un valor nulo
- Agrega un caso de prueba que verifique que ante un catálogo inválido no se levante una excepción al calcularse los indicadores de red
> Arreglo indicadores de red nulos cuando un catálogo es inválido

- pydatajson/custom_exceptions.py
- pydatajson/validation.py
- tests/samples/repeated_downloadURL.json
- tests/support/factories/catalog_errors.py
- tests/support/factories/core_files.py
- tests/test_core.py
Closes #85 
Valida que los recursos tengan `downloadURL` única. Crea una nueva custom exception y la levanta si este campo está duplicado
> 85 validar download url en recursos

- pydatajson/custom_exceptions.py
- pydatajson/validation.py
- tests/results/mismatched_fileName_and_format.json
- tests/samples/mismatched_fileName_and_format.json
- tests/support/factories/core_files.py
Closes #93 
Agrego el test para la validación de extensión de fileName y format. Además cambio la validación para que tenga en cuenta formatos IANA donde el subtipo no es igual a la extensión. Por otro lado, arreglo FileNameExtensionError para que sea un error de validación a diferencia de una excepción.
> 93 validar formatos y filenames

- pydatajson/writers.py
- tests/test_readers_and_writers.py
Si se escribe un catálogo con `write_xlsx_catalog` y luego se intenta leerlo con `read_xlsx_catalog`, se da el siguiente error:
```python
Traceback (most recent call last):
File "/home/federico/Workspace/datos/pydatajson/tests/test_readers_and_writers.py", line 169, in test_read_written_xlsx_catalog
read_catalog = pydatajson.readers.read_xlsx_catalog(tmp_xlsx)
File "/home/federico/Workspace/datos/pydatajson/pydatajson/readers.py", line 223, in read_xlsx_catalog
catalog_dict = read_local_xlsx_catalog(xlsx_path_or_url)
File "/home/federico/Workspace/datos/pydatajson/pydatajson/readers.py", line 411, in read_local_xlsx_catalog
field["distribution_identifier"], field["distribution_title"],
KeyError: 'distribution_title'
```
> Fixes y tests para función write_xlsx_catalog

- docs/MANUAL.md
- pydatajson/ckan_utils.py
- pydatajson/federation.py
- tests/test_ckan_utils.py
Closes #90 
Agrega el parámetro opcional `demote_superTheme` a `push_dataset_to_ckan()`.  Si está en True, propaga los ids de los superTheme a los grupos del paquete de CKAN.
> 90 mover super theme a theme

- docs/MANUAL.md
- pydatajson/ckan_utils.py
- pydatajson/federation.py
- tests/test_ckan_integration.py
- tests/test_ckan_utils.py
- tests/test_federation.py
Closes #103 
Hace que el `catalog_id` sea un parámetro opcional. Si no se pasa, los identificadores de dataset y distribuciones se preservan sin prependear nada.
> 103 catalog id opcional

- pydatajson/ckan_utils.py
- pydatajson/federation.py
- pydatajson/search.py
- tests/samples/full_data.json
- tests/test_ckan_utils.py
- tests/test_federation.py
Closes #130 
-Hace la comparación de id de `themes` de un dataset y su entrada en el `theme_taxonomy` case insensitive
-Remueve caracteres no permitidos de los `labels` de los `themes` cuando se pasan como tags.
> 130 mejorar el manejo de themes

- docs/MANUAL.md
- pydatajson/ckan_utils.py
- pydatajson/federation.py
- tests/test_ckan_utils.py
- tests/test_federation.py
Closes #132 
Implementa la funcionalidad de `push_theme_to_ckan()`.  La función toma un catálogo y un identificador o label de theme y copia la metadata al portal pasado como parámetro de acuerdo a la especificación 1.1 del perfil de metadatos.
> 132 push theme to ckan

- docs/MANUAL.md
- pydatajson/federation.py
- tests/test_federation.py
Implementa 3 wrappers: `harvest_dataset_to_ckan()`, `harvest_catalog_to_ckan()` y `restore_dataset_to_ckan()`. Además agrega el método `push_new_themes()` que escribe en un portal de CKAN los temas no presentes de la taxonomía de un catálogo.
> 128 wrappers para push dataset to ckan

- pydatajson/federation.py
- tests/test_federation.py
Closes #151 
`harvest_catalog()` chequea que la lista no sea `None` y loggea las excepciones de `harvest_dataset()` para continuar la federación.
> 151 robustecer harvest catalog to ckan()

- pydatajson/federation.py
Agrego el caso de que la federación de un dataset falle por validación de CKAN.
> Agrego catcheo de excepciones de validación en harvest_catalog

- MANIFEST.in
- requirements.txt
- requirements_2.7.txt
- setup.py
Closes #156 
Cambia el `setup.py` y los requerimientos para que el marcador de versión esté fuera del txt de requerimientos y pip lo parsee bien.
> fix para functools en py3

- pydatajson/writers.py
- tests/test_readers_and_writers.py
Closes #159 
`superThemeTaxonomy` estaba siendo excluida  a la hora de escribir el catálogo en formato `xlsx`.
Agrega un test con el comportamiento esperado.
> 159 bugfix xlsx writer

- pydatajson/schemas/dataset.json
- pydatajson/schemas/mixed-types.json
- tests/samples/empty_super_theme_list.json
- tests/samples/several_assorted_errors.json
- tests/test_validation.py
Closes #161 
- Agrega validación de palabra no vacía para `keyword`, `theme` y `language `. 
- Agrega validación de lista no vacía para `superTheme` para cubrir el caso de federación.
- Agrega tests del comportamiento
> 161 validacion keywords vacios

- pydatajson/time_series.py
- tests/test_time_series.py
Closes #179 
- Atrapa la excepción en caso de que falle `distribution_has_time_index`.
- Agrega tests del comportamiento,
> 179 robustecer has time index

- pydatajson/validation.py
- tests/test_validation.py
Closes #178 
- En la iteración sobre los errores, crea un dicccionario nuevo en vez de pasar la misma referencia siempre.
- Agrega tests para el formato de lista.
> 178 arreglar formato lista validacion

- .travis.yml
Closes #112 
- Fija piso de 80% en el comando de `nosetests`. EL build falla si la cobertura baja de ese número.
> 112 piso coverage travis

- pydatajson/indicators.py
- tests/test_indicators.py
- Cambia el valor default de indicadores de listas. (https://github.com/datosgobar/pydatajson/blob/master/pydatajson/helpers.py#L258 Interpreta `None` como 0. Eso rompe en los casos de indicadores de listas)
- Actualiza los tests
> Change indicators default value

- docs/MANUAL.md
- pydatajson/federation.py
- tests/test_federation.py
Closes #209 
- Agrega un wrapper sobre la llamada de API para obtener el árbol de organizaciones de un portal.
- Agrega test del método. 
(Refactor del decorador  patch: patchea la clase entera en lugar de cada test particular)
> 209 get organizations from ckan

- docs/MANUAL.md
- pydatajson/federation.py
- tests/test_federation.py
Se creó la función 'get_organization_from_ckan' y su test correspondiente.
Se actualizó la documentación para incluir la existencia de dicha función.
Se corrigió la documentación que involucra a la función 'get_organizations_from_ckan'.
Closes #207.
> 207 get organization from ckan

- docs/MANUAL.md
- pydatajson/federation.py
- tests/test_federation.py
Closes #206 
- Extrae la funcionalidad para crear una organización en `push_organization_to_ckan()`
- Agrega tests de comportamiento
- Agrega documentación
> 206 push organization to ckan

- docs/MANUAL.md
- pydatajson/federation.py
- tests/test_federation.py
Closes #218 
- Agrega método `remove_organization_from_ckan()`.
- Agrega tests del comportamiento.
- Agrega documentación del método.
> 218 remove organization from ckan

- docs/MANUAL.md
- pydatajson/ckan_utils.py
- pydatajson/federation.py
- pydatajson/helpers.py
- tests/test_federation.py
- Las funcionalidades que estaban en `restore_catalog_to_ckan()` pasan a ser de `restore_organization`. `restore_catalog` se compone de varias llamadas a `restore_organization`
- Agrega tests del comportamiento.
> 202 restore multiples organizaciones

- docs/MANUAL.md
- pydatajson/ckan_utils.py
- pydatajson/federation.py
- pydatajson/helpers.py
- tests/test_federation.py
- Agrega un nuevo parámetro opcional a `push_dataset_to_ckan()`. `generate_access_url`, toma una lista de identificadores de distribuciones. Las distribuciones de esa lista regeneran el campo `accessURL` de acuerdo al portal de destino. Las que no están en esa lista, mantienen el campo (el comportamiento anterior).
- Agrega tests del nuevo parámetro y modifica los existentes para adptarlo.
> 222 regenerar accessurl

- pydatajson/indicators.py
- tests/test_indicators.py
Closes #226 
- Saca la linea que fuerza catalogo central en el cálculo de indicadores
- Agrega test verificando que no se calculan los indicadores de federación
> 226 Indicadores de federación opcionales

- pydatajson/custom_exceptions.py
- pydatajson/readers.py
- tests/samples/full_data
- tests/test_readers_and_writers.py
Closes datosgobar/django-datajsonar#88
- Ante ausencia de sufijo, el lector de DataJson asume que el formato es JSON
- Cambia la excepción que lanza en caso de no poder parsear, para fallar de manera más controlada
- Agrega tests del comportamiento
> 88 extension lectura json

- pydatajson/catalog_readme.py
- pydatajson/core.py
- pydatajson/templates/catalog_readme.txt
- tests/cassetes/test_generate_readme_with_null_indicators.yaml
- tests/cassetes/test_readme_file_write.yaml
- tests/results/catalog_readme.md
- tests/results/null_indicators_readme.md
- tests/test_catalog_readme.py
- tests/test_core.py
- tests/test_search.py
Closes #248 
- Extrae la escritura del readme a un módulo aparte
- Extrae los tests de `test_core` y agrega el caso con indicadores nulos
> 248 refactor readme

- pydatajson/writers.py
- tests/test_readers_and_writers.py
Closes datosgobar/django-datajsonar#125
- Defaultea a lista vacía si no hay themes en el dataset (similar al caso de fields y distribuciones)
- Agrega caso de test de catálogo sin themes
> 125 xlsx writer bugfix

- pydatajson/core.py
- pydatajson/custom_exceptions.py
- pydatajson/response_formatters/__init__.py
- pydatajson/response_formatters/dict_formatter.py
- pydatajson/response_formatters/list_formatter.py
- pydatajson/response_formatters/tables_formatter.py
- pydatajson/response_formatters/validation_response_formatter.py
- pydatajson/validation.py
- pydatajson/validation_formatter.py
Modifica funciones sueltas de `validations.py` en varias clases. Se asegura que no se rompe el comportamiento anterior con los tests unitarios existentes.
> Refactor de validaciones

- pydatajson/ckan_utils.py
- pydatajson/custom_remote_ckan.py
- pydatajson/federation.py
Closes #235 
- Los métodos que toman un catálogo DataJson usan el `requests_timeout` y `verify_ssl`
- Si no toman un catálogo, se le pueden pasar esos parámetros por kwargs
> Agrego parametros de timeout y verficación de ssl

- pydatajson/custom_exceptions.py
- pydatajson/federation.py
- tests/samples/numeric_distribution_identifier.json
- tests/test_federation.py
- Creo excepción específica para distribuciones cuyos identificadores son puramente numéricos
- Agrego paso de validación de las distribuciones de los datasets al querer restaurar datasets
- Agrego caso de test para un .json con una distribución puramente numérica, y otra no puramente numérica
Closes #262
> 262 validar ids recursos federables no puramente numericos

- pydatajson/readers.py
Evita condiciones de carrera en contextos de múltiples procesos intentando leer catálogos y escribiendo
archivos temporales a la misma ruta.
Closes #272
> Uso NamedTemporaryFile en lectura de catálogos en XLSX

- pydatajson/ckan_utils.py
- pydatajson/constants.py
- requirements.txt
- tests/test_ckan_utils.py
Se cambió el modo en el que se enviaban las fechas a ckan, en vez de usar UTC por defecto se empieza a usar GMT-3.
closes #274
> Uso de default GMT -03:00

- pydatajson/helpers.py
- pydatajson/indicators.py
- tests/test_helpers.py
- tests/test_indicators.py
- Agrego una validacion en la creacion del campo de frecuencia de un dataset, para mantener solamente el campo 'EVENTUAL' en mayusculas
- Agrego helper que convierte los fields de un diccionario a uppercase, y lo uso para convertir los formatos del indicador a mayusculas
Closes #273
> 273 frecuencias formatos uppercase

- pydatajson/ckan_utils.py
- pydatajson/federation.py
- tests/test_ckan_utils.py
- tests/test_federation.py
Se agrego los parametros opcionales origin_tz y dst_tz para que se usen desde monitoreo.
> 276 agregar parametros timezones origen y destino

- pydatajson/federation.py
Closes #286 
- Durante la restauración, si ocurría un error de requests, no se atrapaba y se cortaba la restauración de la organización entera. Se considera ese caso
> Atrapo errores de request al momento de restaurar un dataset

- pydatajson/helpers.py
- tests/test_helpers.py
- tests/test_indicators.py
Closes https://github.com/datosgobar/monitoreo-apertura/issues/234
- Para el helper `fields_to_uppercase` contemplo el caso de mayusculas y minusculas mixtas en un field, y lo paso a mayusculas
- Creo test para este caso
- Cambio tests para reflejar este cambio
> Fields con upper y lower case mixtos se cambian a uppercase

- pydatajson/core.py
- pydatajson/indicators.py
- pydatajson/validation.py
- tests/test_indicators.py
- tests/test_urls_validation.py
Closes https://github.com/datosgobar/monitoreo-apertura/issues/257
- Creo parámetros booleanos para los métodos de validación de catálogos que determinan si validar o no los campos de URLs. Por default no se validan las URL.
- Extraigo generación de indicadores de campos de URLs en función aparte, que crean o no según otro parámetro booleano de la generación de indicadores de catálogos
- Refactorizo tests existentes y agrego uno nuevo para el caso default
> Validacion de urls opcional

- pydatajson/backup.py
- pydatajson/schemas/distribution.json
- tests/test_validation.py
- Cambio el regex del json schema que se usa para la validacion de filenames de distribucion. Ahora acepta cualquier tipo de caracter para el nombre de archivo.
- Elimino error esperado de un caso de test, donde se esperaba un mensaje de error relacionado a un filename invalido.
Closes #299
> Cambio la validacion de filenames de una distribucion

- pydatajson/schemas/distribution.json
- pydatajson/validators/consistent_distribution_fields_validator.py
- tests/samples/border_cases_ditribution_filenames.json
- tests/samples/invalid_ditribution_filenames.json
- tests/test_validation.py
Se deja que la validación de filenames de distribuciones puedan ser vacios o null, casos como números deben fallar.
closes #299
> Validacion ligera filenames
